<?php
$title = 'dodaj nowego usera';
$this->headTitle($title);
?>
<div class="well well-lg well-margin"><h3><?php echo $this->escapeHtml($title); ?><h3></div>
            <?php
            $form = $this->form;
            $form->setAttribute('class', 'form-horizontal');
            $form->setAttribute('action', $this->url('admin', array('action' => 'add')));

            $form->prepare();

            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('id'));
            ?>
            <div class="form-group">
                <?php
                echo $this->formlabel($form->get('role_id'));
                echo $this->formElement($form->get('role_id'));
                echo $this->formElementErrors($form->get('role_id'));
                ?>
            </div>
            <div class="form-group">
                <?php
                echo $this->formlabel($form->get('permission_id'));
                echo $this->formElement($form->get('permission_id'));
                echo $this->formElementErrors($form->get('permission_id'));
                ?>
            </div>   
            <div class="form-group">
                <?php
                echo $this->formlabel($form->get('resource_id'));
                echo $this->formElement($form->get('resource_id'));
                echo $this->formElementErrors($form->get('resource_id'));
                ?>
            </div> 
            <div class="form-group">
                <?php
                echo $this->formInput($form->get('submit'));
                echo '   <a class="btn btn-danger" href="javascript:history.back();">Wstecz</a>';
                echo $this->form()->closeTag($form);
                ?>
            </div>


