<?php
$title = 'Zmiana danych logowania';

$this->headTitle($title);
?>
<div class="well well-lg well-margin"><h3><?php echo $this->escapeHtml($title); ?><h3></div>

<?php
$form = $this->form;

$form->setAttribute('action', $this->url('admin', array('action' => 'edit', 'id' => $this->id)));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>
<div class="form-group">
    <?php
    echo $this->formlabel($form->get('email'));
    echo $this->formElement($form->get('email'));
    ?>
</div>
<div class="form-group">
    <?php
    echo $this->formlabel($form->get('password'));
    echo $this->formElement($form->get('password'));
    ?>
</div>
<div class="form-group">
    <?php
    echo $this->formInput($form->get('submit'));
    echo '   <a class="btn btn-danger" href="javascript:history.back();">Wstecz</a>';
    echo $this->form()->closeTag($form);
    ?>
</div>
