<?php
$title = 'Działy';
$this->headTitle($title);
$url_order = 'ASC';
if ($order_by == 'imie') {
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
} elseif ($order_by == 'nazwisko') {
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
} elseif ($order_by == 'dzial') {
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
}
?>

<div id="wyszukaj" class="row">
    <table>
        <?php
        $form = $this->form;
        $form->setAttribute('class', 'form-vertical');
        $form->setAttribute('action', $this->url('uzytkownik', array('action' => 'dzial')));
        $form->prepare();

        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('id'));
        ?>
        <div class="col-md-2">
            <?php echo $this->formElement($form->get('dzial_id')); ?>
            <?php //echo $this->formRow($form->get('dzial_id')); ?>
        </div><div class="col-md-2">
            <?php echo $this->formInput($form->get('submit')); ?>
        </div>
        <?php echo $this->form()->closeTag($form); ?>
    </table>

</div>
<h2><span class="label label-warning">&nbsp<?php echo $this->dzial; ?></span></h2>
<?php
//****komputer

    echo "<table class='table table-hover'><thead class='thead-inverse'><th><h3><span class='label label-info'>Komputer</span></h3></th><th>Nazwisko Imię</th><th>sn</th><th>Nr ewidencyjny</th><th>Nr inwentarzowy</th><th>Data zakupu</th></thead>";
    echo "<tbody>";
    foreach ($komputer as $pc) :
        //if ($pc->uzytkownik_id == $uzytkownik->id) {

        echo "<tr><td><a href='";
        echo $this->url('komputer', array('action' => 'detail', 'id' => $pc->id)); ///detail/');
        //echo $pc->id;
        echo "'>";
        echo $pc->marka;
        echo "  ";
        echo $pc->model;
        echo "</a></td>";
        echo "<td>" . $pc->nazwisko . " " . $pc->imie . "</td>";
        echo "<td>";
        echo $pc->sn;
        echo "</td><td>";
        echo $pc->nr_ewid;
        echo "</td><td>";
        echo $pc->nr_inwent;
        echo "</td><td>";
        echo $pc->data_zakupu;
        echo "</td><td>";
        echo $pc->dzial;
        echo "</td></tr>";
        //   }
    endforeach;
    echo "</tbody></table>";

?>
<?php
//****telefon

//if (($telefon > 0) && (!$this->telefon == NULL)) {
    echo "<table class='table table-hover'><thead class='thead-inverse'><th><h3><span class='label label-info'>Telefon</span></h3></th><th>Nazwisko Imię</th><th>sn</th><th>IMEI</th><th>Nr inwentarzowy</th><th>Data zakupu</th></thead>";
    echo "<tbody>";
    foreach ($telefon as $tel) :
        //if ($pc->uzytkownik_id == $uzytkownik->id) {

        echo "<tr><td><a href='";
        echo $this->url('telefon', array('action' => 'detail', 'id' => $tel->id)); ///detail/');
        //echo $pc->id;
        echo "'>";
        echo $tel->marka;
        echo "  ";
        echo $tel->model;
        echo "</a></td>";
        echo "<td>" . $tel->nazwisko . " " . $tel->imie . "</td>";
        echo "<td>";
        echo $tel->sn;
        echo "</td><td>";
        echo $tel->nr_ewid;
        echo "</td><td>";
        echo $tel->nr_inwent;
        echo "</td><td>";
        echo $tel->data_zakupu;
        echo "</td><td>";
        echo $tel->dzial;
        echo "</td></tr>";
        //   }
    endforeach;
    echo "</tbody></table>";

?>