<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body>
        <script>
            $(function () {
                $.each($('.linklist li'), function (key, value) {

                    var el = $(value);
                    var link = el.find('a').attr('href');
                    var dif = link.localeCompare(window.location.pathname);
                    var dif2 = ("/" + link).localeCompare(window.location.pathname);

                    if (dif === 0 || dif2 === 0) {
                        el.addClass('active');
                    }

                });
            });
        </script>
        <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                </div>

                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav linklist">
                        <li><a href="<?php echo $this->url('uzytkownik') ?>"><span class="glyphicon glyphicon-user">&nbsp<?php echo $this->translate('Uzytkownik') ?></span></a></li>
                        <li><a href="<?php echo $this->url('komputer') ?>"><span class="glyphicon glyphicon-hdd">&nbsp<?php echo $this->translate('Komputer') ?></span></a></li>
                        <li><a href="<?php echo $this->url('telefon') ?>"><span class="glyphicon glyphicon-phone">&nbsp<?php echo $this->translate('Telefony') ?></span></a></li>
                        <li><a href="<?php echo $this->url('uzytkownik', array('action' => 'dzial')) ?>"><span class="glyphicon glyphicon-phone">&nbsp<?php echo $this->translate('Raport-Dział') ?></span></a></li>
                        <li><a href="<?php echo $this->url('uzytkownik', array('action' => 'osoba')) ?>"><span class="glyphicon glyphicon-phone">&nbsp<?php echo $this->translate('Raport-Osoba') ?></span></a></li>
                        <li><a href="<?php //echo $this->url('logout',array('action'=>'logout'))  ?>"><span class="glyphicon glyphicon-off">&nbsp<?php echo $this->translate('Wyloguj') ?></span></a></li>

                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
        <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by DeeTriX <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
<?php echo $this->inlineScript() ?>
    </body>
</html>
